version: "3.8"
services:
    web:
      build: .
      image: anthonybrochu/rubik:latest
      ports:
        - "8000:3000"
      environment:
        - ADMIN_EMAILS=email@local.com
        - AIRBRAKE_PROJECT_ID=1234
        - AIRBRAKE_API_KEY=1234
        - COMMENT_EMAIL_RECIPIENT=email@local.com
        - GA_ANALYTICS_ID=""
        - GOOGLE_AD_CLIENT=""
        - GOOGLE_OAUTH_CLIENT_ID=some_client_id
        - GOOGLE_OAUTH_CLIENT_SECRET=some_client_secret
        - DATABASE_URL=mysql2://<username>:<pass>@<host>:<port>/<db_name>
        - RAILS_ENV=development
        - SECRET_KEY_BASE=
        - SENDGRID_USERNAME=apikey
        - SENDGRID_PASSWORD=
        - REDIS_URL=redis://redis:6379/0
    redis:
      image: redis
      ports:
        - "6739:6739"